### ISSUE TITLE
Add NovaCore as a dependency

### ISSUE THREAD

**Issue by Vexatos** [NOVAAPI/NovaWrapper-MC1.7.10#2]
Any o(pi)nions?

**Comment by RX14** [comment]
@Vexatos I would prefer getting it from maven rather than using a submodule, as the wrapper should probably only target API releases so the projects are weakly linked. Git submodules confuse many and are discouraged in favour of proper dependency management, but I would like @asiekierka 's opinion.

**Comment by Kubuxu** [comment]
@RX14 Is there any way to create general test suite for wrappers? Using submodule would allow us to run tests form Core on Wrappers.

**Comment by RX14** [comment]
@Kubuxu you can package tests as maven packages too, you just add the deps to `testCompile`.

We could use gradle to generate a core test suite as a maven package then require it in the wrappers, IMHO a cleaner solution.

**Comment by Kubuxu** [comment]
Ok.

**Comment by RX14** [comment]
This is done
