### ISSUE TITLE
Licencing

### ISSUE THREAD

**Issue by Kubuxu** [NOVAAPI/NovaWrapper-MC1.7.10#5]
We need permission to licence this repository (NovaWrapper-MC1.7.10) under LGPLv3:

- [x] @calclavia 
- [x] @RX14 
- [x] @magik6k 
- [x] @asiekierka 
- [x] @Kubuxu

**Comment by asiekierka** [comment]
OK

**Comment by RX14** [comment]
Permission granted

**Comment by magik6k** [comment]
Permission granted

**Comment by Kubuxu** [comment]
@calclavia can you grant permission under this issue. You know, formalities.
